server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "020316"
    url: jdbc:mysql://localhost:3306/moqiang_navigation?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

#mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false